name: Node CI

on: [push, pull_request]
jobs:
  test:
    name: v18 @ ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint --if-present
